import { ReactNode } from "react";

import "./_styles/global.scss";

import { Providers } from "./_providers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "travis",
  description: "Generated by lldan & itrostik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
